default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: 3306
  username: root
  password: linhnguyen1411

development:
  <<: *default
  database: bds_development

test:
  <<: *default
  database: bds_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
