default: &default
  adapter: mysql2
  pool: 5
  username: root
  password: linhnguyen1411
  socket: /var/run/mysqld/mysqld.sock
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: realty_development

test:
  <<: *default
  database: realty_test

production:
  <<: *default
  database: realty_production
  username: linhnguyen1411
  password:
