default: &default
  adapter: mysql2
  pool: 5
  username: root
  password:
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: realty_v1_development

test:
  <<: *default
  database: realty_v1_test

production:
  <<: *default
  database: realty_v1_production
  username: linhnguyen1411
  password:
